#!/bin/sh -ex
tmp=$(git-hooks-workdir "$@")
trap 'rm -rf "$tmp"' INT TERM EXIT HUP

dest="/srv/www/htdocs/atelier-fu"

cd "$tmp"
bin/make-pages "$dest"
cp -r img images *.css *.ttf *.js p "$dest"
ln -sf p/index.html "$dest"
